add api for getting flow circulating supply on canto
Velocimeter/frontend pull request #25
Opened 2023-04-05 02:18 UTC by oxSaturn

So this pull request will add a new api at `https://www.velocimeter.xyz/api/canto/circulating-supply` which would return data per coingecko's requirements https://docs.google.com/document/d/1v27QFoQq1SKT3Priq3aqPgB70Xd_PnDzbOCiuoCyixw/edit#heading=h.pydh6ytf8qyc

<img width="748" alt="" src="https://user-images.githubusercontent.com/126733611/229963479-6f68f75f-887e-491b-9362-154b2035edbc.png">

I'm using viem here because I noticed that @t0rbik is refactoring code with viem in https://github.com/Velocimeter/frontend/tree/breaking/viem.

2023-04-05 02:22 UTC, oxSaturn commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +  abi: [
Note that I'm not importing the abi here because the abi is in a `.js` file instead of `.ts`. And enabling type inference would require rewriting `.js` to `.ts` and append a `as const` which would cause a lot of typing errors at the moment.

2023-04-05 03:37 UTC, t0rbik requested changes

2023-04-05 03:37 UTC, t0rbik commented on Frontend-v1-Original/pnpm-lock.yaml
Can we remove it? we dont use pnpm, we use yarn

2023-04-05 03:37 UTC, t0rbik commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +const publicClient = createPublicClient({
Could you initialize publicClient same way as here [this](https://github.com/Velocimeter/frontend/blob/breaking/viem/Frontend-v1-Original/stores/connectors/viem.ts)?

2023-04-05 03:37 UTC, t0rbik commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +const publicClient = createPublicClient({
So we can rely on multiple rpc urls

2023-04-05 03:37 UTC, t0rbik commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +  abi: [
sounds good. we will make it better after #24 gets merged

2023-04-05 03:37 UTC, t0rbik commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +    ) / Math.pow(10, NATIVE_TOKEN.decimals);
can we use [this ](https://github.com/Velocimeter/frontend/blob/0e96d5606d431efb205b38fa1c775f9f44043eb1/Frontend-v1-Original/stores/helperStore.ts#L81) code for consistency?

2023-04-05 05:09 UTC, oxSaturn commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +    ) / Math.pow(10, NATIVE_TOKEN.decimals);
If we're not urgent to get this api live, how about continue it after #24 so we don't have to duplicate code?

2023-04-05 07:15 UTC, t0rbik commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +    ) / Math.pow(10, NATIVE_TOKEN.decimals);
> If we're not urgent to get this api live, how about continue it after #24 so we don't have to duplicate code?

1. its kind of urgent because CG guys are waiting for it.
2. not sure #24 will be ready to merge today.
3. next apu is kind of isolated so i say we dont worry about duplicated code for now

gonna autorise vercel, lets see if it works the way it is rn

2023-04-05 08:35 UTC, oxSaturn commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +    ) / Math.pow(10, NATIVE_TOKEN.decimals);
Updated.

2023-04-05 09:45 UTC, t0rbik commented
@oxSaturn hey im thinking rn...
can we do this endpoint to be accessible only from exactly defined origins? like we're going to expose it to public and it creates possibility of abstract attacker doing ddos or something related

2023-04-05 10:32 UTC, oxSaturn commented
> @oxSaturn hey im thinking rn... can we do this endpoint to be accessible only from exactly defined origins? like we're going to expose it to public and it creates possibility of abstract attacker doing ddos or something related
> 
> [Array - set origin to an array of valid origins. Each origin can be a String or a RegExp. For example ["http://example1.com", /.example2.com$/] will accept any request from "http://example1.com/" or from a subdomain of "example2.com".](https://github.com/expressjs/cors#configuration-options)

yeah, we can definitely set the `origin`. Do you know which origin Coingecko uses to fetch the data?

2023-04-05 10:56 UTC, t0rbik commented
Waiting GC to send over their origin

2023-04-05 12:06 UTC, t0rbik commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +      interval: 12_000,
Assuming themselved are on pro CG api lets set it to 30_000
Here's reference in CG api:
This depends - but endpoints are all cached to around 1 to 5 minutes and you can expect most data to be updated at similar intervals unless otherwise specified. Pro API (paid plans) generally have faster update frequency, i.e. 30 sec for simple/price endpoint

2023-04-05 12:51 UTC, t0rbik commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +      interval: 12_000,
@oxSaturn i see now they are polling every 30 mins. so we can make it 900_000

2023-04-05 12:51 UTC, t0rbik commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
> +
@oxSaturn dont need it if they polling every 30 mins

2023-04-05 12:52 UTC, t0rbik commented
@oxSaturn let me know if u will make any changes or i will finalise it myself

2023-04-05 13:02 UTC, oxSaturn commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
>  import Cors from "cors";
Better to enforce the styling with an eslint plugin when possible, e.g., https://github.com/import-js/eslint-plugin-import/blob/main/docs/rules/newline-after-import.md

2023-04-05 13:21 UTC, t0rbik approved these changes
looks good

2023-04-05 13:21 UTC, t0rbik commented on Frontend-v1-Original/pages/api/canto/circulating-supply.ts
>  import Cors from "cors";
obv on the list. as well as `run next lint`.

2023-04-06 02:56 UTC, t0rbik approved these changes

2023-04-06 03:01 UTC, merged

2023-04-06 03:02 UTC, t0rbik commented
merged