add UI for nft merging
Velocimeter/frontend pull request #49
Opened 2023-04-19 01:31 UTC by oxSaturn

Closes https://app.dework.xyz/velocimeter/main-space-58499?taskId=da58b451-720a-4123-a35b-dfd720b26d6d

2023-04-19 04:51 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVest/MergeNFT.tsx
> +    }
This is for the use case where users would access `/vest/[id]/merge` url directly or they refresh the page causing `nfts` data to be cleaned.

Might need a loading indicator.

2023-04-19 04:55 UTC, oxSaturn commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +            attached: attached,
This `voted` only means the nft is not voted in current epoch, it doesn't tell us whether it's voted in the past epoch. That's why we need a `attached` to tell users whether they should reset the nft first when merging it into others.

2023-04-19 08:05 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +          const [[lockedAmount, lockedEnd], lockValue, attached] =
seems like it creates another confusion, because there's `attached ` view on voting escrow as well, but we are reading `voted ` here

2023-04-19 08:07 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +        [BigInt(from), BigInt(to)],
Not sure if we need BigInt here? It's a web3.js contract interaction

2023-04-19 08:09 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +        "You have already voted with this token or your nft is attached, try to reset first",
hm. there's no way to encounter attached in our system, because we do not attach nfts on frontend and I doubt someone will do it manually when adding liquidity

2023-04-19 08:13 UTC, t0rbik commented on Frontend-v1-Original/components/ssVest/MergeNFT.tsx
> +import { ACTIONS } from "../../stores/constants/constants";
I remember you were saying about linter, but we didnt get to it. so can we just make it so npm packages on top, empty line and then internal imports

2023-04-19 08:16 UTC, t0rbik commented on Frontend-v1-Original/components/ssVest/MergeNFT.tsx
> +            onClick={() => onMergeNFT(id as string, selectedNFTId as string)}
I wouldnt cast `selectedNFTid ` to string and refactor `onMergeNFT ` to make second argument `string | null` . then just check in function body so if `to `is `null`, do nothing

2023-04-19 08:18 UTC, oxSaturn commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +          const [[lockedAmount, lockedEnd], lockValue, attached] =
I used `attached` here because when you merge a nft voted in the past but not current epoch, you'll get this error: `"You have already voted with this token or your nft is attached"`.

<img width="989" alt="CleanShot 2023-04-19 at 16 16 18@2x" src="https://user-images.githubusercontent.com/126733611/233012750-8f34ec00-8287-41b6-be10-f0a2af36b365.png">

So yeah, sounds a bad naming here. Do you have any suggestion?

2023-04-19 08:19 UTC, t0rbik commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +                        ) : null}
maybe instead of not showing button make it disabled if `votedThisEpoch`?

2023-04-19 08:19 UTC, oxSaturn commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +        "You have already voted with this token or your nft is attached, try to reset first",
right, this can be reverted as uses shouldn't be able to access the merge UI for `attached` nft now.

2023-04-19 08:22 UTC, t0rbik commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +                              title={`Please Reset NFT before merging as it's attached.`}
We can add this check to mergeNFT in stableSwapStore and make them reset it if it's ~~attached~~ voted ever

2023-04-19 08:23 UTC, t0rbik commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +                              title={`Please Reset NFT before merging as it's attached.`}
add this tx to queue for them

2023-04-19 08:26 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +  getVestNFTs = async (): Promise<VestNFT[]> => {
it's a debateble thing to type return type of functions. it will overwrite the actual return type in some cases. we can define a constant of type and return it, and typescript will inherit.
[reference](https://youtu.be/I6V2FkW1ozQ)

2023-04-19 08:26 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +                                {row.attached ? "or merge " : ""}NFT.
A nft voted in the past but not this epoch should be reset first to merge.

A nft never voted can be merge without reset.

2023-04-19 08:26 UTC, t0rbik requested changes
Sorry for single comments, just a glance ended up to reviewing whole thing

2023-04-19 08:27 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +                                {row.attached ? "or merge " : ""}NFT.
I think this change is not really necessary, no one would pay attention to the discrepancy of two different tooltips.

2023-04-19 08:27 UTC, t0rbik commented on Frontend-v1-Original/components/ssVest/MergeNFT.tsx
> +import { ACTIONS } from "../../stores/constants/constants";
you can do it if you want/have time

2023-04-19 08:33 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +          const [[lockedAmount, lockedEnd], lockValue, attached] =
'voted' ptobably? lol

2023-04-19 08:57 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVest/MergeNFT.tsx
> +import { ACTIONS } from "../../stores/constants/constants";
will do it in another pr so not to messing up this one.

2023-04-19 13:03 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +                              title={`Please Reset NFT before merging as it's attached.`}
Would love to, but we'll have to copy almost all code inside `resetVest` to `mergeNft` as the `reset` actually includes three transactions:
```
{
            uuid: rewardsTXID,
            description: `Checking unclaimed bribes`,
            status: "WAITING",
          },
          {
            uuid: rebaseTXID,
            description: `Checking unclaimed rebase distribution`,
            status: "WAITING",
          },
          {
            uuid: resetTXID,
            description: `Resetting your veNFT`,
            status: "WAITING",
          },
```

Another way is doing it in two steps, but it looks weird too IMO:

```
if (reset) {
        await this.resetVest({ type: "internal", content: { tokenID: from } })
      }
// ... merging code after
```

2023-04-20 12:26 UTC, oxSaturn commented
![](https://user-images.githubusercontent.com/126733611/233364218-d90ce2c1-3cf7-431f-95fa-cfd2d5818bf1.png)

Ok, this is the best I can do now. 

1. A new column named `Reset` was introduced, so users can tell it's either reset or voted in current epoch.
2. The `Last Voted` date time was put under `Voted` to show whether it's voted in the past, which is helpful to track the last vote
3. An `Alert` on the top of table showing the rules we have.

2023-04-21 08:29 UTC, t0rbik reviewed
"NOTE" is just for future refactors

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/components/ssVest/MergeNFT.tsx
> +                          <Typography color={"textSecondary"}>
why curly braces?

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +        </Alert>
NOTE: to be changed in next deployment.

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
NOTE: everything here probably would need to be reconsidered in next deployment.

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +                        )}
Do you think we could swap Merge with Manage, so that buttons that can be in disabled stated will be placed next to each other?

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +            reset: actionedInCurrentEpoch && !voted,
👍

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +                          Number(row?.lastVoted) !== 0) ||
Number(undefined) = NaN

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +                            ).toLocaleString()}
Number(undefined) * 1000 = NaN
new Date(NaN).toLocaleString() = 'Invalid Date'

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +            lastVoted,
lets make last voted required field?

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +          });
this is being done in call contract wait anyways?

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +          });
on receipt event tx gets marked as confirmed, transaction queue gets updated [here](https://github.com/Velocimeter/frontend/blob/aed3d43540cb7e9c5377758040fc506c6fda69f9/Frontend-v1-Original/components/transactionQueue/transactionQueue.tsx#L98).

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +          });
[confirmed](https://github.com/Velocimeter/frontend/blob/aed3d43540cb7e9c5377758040fc506c6fda69f9/Frontend-v1-Original/components/transactionQueue/transaction.tsx#L32) marks tx with same icon as done.

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
>      const _lastVoted = await viemClient.readContract({
you can call _checkNFTLastVoted in here as well.

2023-04-21 08:29 UTC, t0rbik commented on Frontend-v1-Original/stores/types/types.ts
> +  lastVoted?: bigint;
wouldnt it be better to make it required field?

2023-04-21 11:35 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVest/MergeNFT.tsx
> +  }, [router]);
We would redirect to `/vest` page when merged successfully:

```
const nftMerged = () => {
      router.push("/vest");
    };
```
So I don't think passing `router.query.id` is right.

2023-04-21 11:40 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +                        )}
Good idea.

2023-04-21 11:42 UTC, oxSaturn commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +            lastVoted,
So far it's only used in one place, i.e. `getVestNFTs`, that's why I made it optional. But yeah, I think it might be better to keep consistence.

2023-04-21 12:08 UTC, oxSaturn commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +    return [actionedInCurrentEpoch, _lastVoted];
Note that I've rewritten this function to return two values here so we don't have to call `_checkNFTLastVoted` another time in other functions to get its value which would issue another rpc request.

2023-04-21 12:27 UTC, oxSaturn commented
btw, not sure if you have this `Squash and merge` button when merging pull requests:

<img width="746" alt="" src="https://user-images.githubusercontent.com/126733611/233634162-ff852fee-eec9-477d-b97d-352e348165f8.png">

I reckon it could make the timeline of branch more clear, e.g.,

<img width="681" alt="" src="https://user-images.githubusercontent.com/126733611/233635126-b7530b86-62bb-42fa-8457-34f9c179b3f3.png">

2023-04-21 12:27 UTC, oxSaturn commented on Frontend-v1-Original/stores/types/types.ts
> +  lastVoted?: bigint;
solved.

2023-04-23 08:50 UTC, t0rbik requested changes

2023-04-23 08:50 UTC, t0rbik commented on Frontend-v1-Original/stores/stableSwapStore.ts
> +  ): Promise<[boolean, bigint]> => {
lets do last thing: instead of casting return type of function, cast `[false, _lastVoted] as const` and `[actionedInCurrentEpoch, _lastVoted] as const`

2023-04-23 12:26 UTC, t0rbik approved these changes

2023-04-23 12:28 UTC, t0rbik commented
you probably need to run yarn tsc as vercel gives typescript errors on deployment try

2023-04-23 12:54 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVest/existingLock.tsx
> +      lastVoted: nft.lastVoted,
Will `updateLockDuration` reset those values?

2023-04-23 13:02 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVest/existingLock.tsx
> +        lastVoted: nft.lastVoted,
Doesn't seem matter as I found those properties are not used in `VestingInfo`.

2023-04-23 13:10 UTC, oxSaturn commented
We should enable https://github.com/okonet/lint-staged to run linters.

2023-04-23 13:13 UTC, t0rbik approved these changes

2023-04-23 13:32 UTC, t0rbik commented
> We should enable https://github.com/okonet/lint-staged to run linters like `tsc` or `eslint`.

of course, lets do after eslint is enabled?

2023-04-24 02:04 UTC, oxSaturn commented
> > We should enable https://github.com/okonet/lint-staged to run linters like `tsc` or `eslint`.
> 
> of course, lets do after eslint is enabled?

Sure.

2023-04-24 03:11 UTC, merged