ui wrangling
Velocimeter/frontend pull request #64
Opened 2023-04-25 15:56 UTC by h1kupz

Still a lot to do but if you have time to review and give feedback... feel free to delete pr if is not of use.

- custom colours added to tailwind.config
- background, nav, info and wallet have been edited.
- have created /common/components for elements across pages.
- numerous module.css files have been removed and tailwind added.
- minor additions to global.css
- have started editing mobile header/nav for mobile.
- still a lot of components that haven't been edited and some MUI elements need more work....

Not sure if a separate deployment of the front end is possible (beta) to be able to work on everything... some things don't load on my local instance.

![Screenshot_20230425_223856](https://user-images.githubusercontent.com/100068908/234332766-bdaf57ee-6266-4932-8050-8d5e062bf193.png)
![Screenshot_20230425_223933](https://user-images.githubusercontent.com/100068908/234332800-274c7a1b-0db7-4b81-9ff0-abfe123fbef7.png)
![Screenshot_20230425_223951](https://user-images.githubusercontent.com/100068908/234332815-0be631f2-9b26-4639-a6b5-a66ff12404c9.png)

2023-04-26 07:04 UTC, t0rbik requested changes
NOTEs are just notes to check again

2023-04-26 07:04 UTC, t0rbik commented on Frontend-v1-Original/components/common/VmPagination.tsx
> +  gauges?: any[];
Seems like we dont need it at all?

2023-04-26 07:04 UTC, t0rbik commented on Frontend-v1-Original/components/common/VmButton.tsx
I feel like this component has been forgotten to be imported in several components. I've seen classes deleted but prev Button component being used instead of VmButton

2023-04-26 07:07 UTC, t0rbik commented
Also could you resolve conflicts?

2023-04-26 09:14 UTC, h1kupz commented on Frontend-v1-Original/components/common/VmBox.tsx
> +  ...rest
Have added HTMLProps (not sure if this is what you meant) to VmBox and removed amountError, assetError & rest. 

At this stage VmBox has not been used very much but is set up as a panel/box to be used inside of panel elements such as on the swap.

2023-04-26 09:15 UTC, h1kupz commented on Frontend-v1-Original/components/common/VmButton.tsx
> +const VmButton = ({ children, className = "", ...rest }: VmButtonProps) => {
...rest on VmButton is used to pass any undeclared props such as:
variant="contained"
color="secondary"
startIcon={<EnhancedEncryptionOutlined />}
size="large"
onClick={onCreate}

I didn't want to mess with much of the MUI at this stage and was just looking to create a styled wrapper for what is there atm.

2023-04-26 09:15 UTC, h1kupz commented on Frontend-v1-Original/components/common/VmPagination.tsx
> +  gauges?: any[];
Removed.

2023-04-26 09:16 UTC, h1kupz commented on Frontend-v1-Original/components/common/index.tsx
> +export { default as VmPagination } from "./VmPagination";
Done.

2023-04-26 09:16 UTC, h1kupz commented on Frontend-v1-Original/components/header/header.tsx
> +                    disableElevation
Visual style is now being handled by the VmPanel wrapper.

2023-04-26 09:17 UTC, h1kupz commented on Frontend-v1-Original/components/header/mobileHeader.tsx
> +          className="hidden cursor-pointer items-center justify-center md:flex"
Removed.

2023-04-26 09:18 UTC, h1kupz commented on Frontend-v1-Original/components/layout/layout.tsx
> +            <div className="fixed top-4 z-10 m-0 block w-full backdrop-blur-sm md:hidden">
Removed.

2023-04-26 09:19 UTC, h1kupz commented on Frontend-v1-Original/components/ssRewards/ssRewardsTable.tsx
> +    event: React.MouseEvent<HTMLButtonElement, MouseEvent> | null | unknown,
Throws an error without the addition of unknown due (I think to React.MouseEvent<unknown>) which is passed into VmPanel.

2023-04-26 09:19 UTC, h1kupz commented on Frontend-v1-Original/components/ssRewards/ssRewardsTable.tsx
> +            gauges={[]}
Removed.

2023-04-26 09:19 UTC, h1kupz commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +    event: React.MouseEvent<HTMLButtonElement, MouseEvent> | null | unknown,
As above error without.

2023-04-26 09:20 UTC, h1kupz commented on Frontend-v1-Original/components/ssVests/ssVestsTable.tsx
> +          gauges={[]}
Removed.

2023-04-26 09:20 UTC, h1kupz commented on Frontend-v1-Original/components/ssVotes/ssVotesTable.tsx
> +    event: React.MouseEvent<HTMLButtonElement, MouseEvent> | null | unknown,
As above error without.

2023-04-26 09:20 UTC, h1kupz commented on Frontend-v1-Original/components/common/VmButton.tsx
Yes there a a few pages/components that have not been updated. Smaller Buttons are also used elsewhere that I have not edited. Atm VmButton has been applied to larger instances such as Swap, Create Vest, etc.

2023-05-02 08:03 UTC, t0rbik commented on Frontend-v1-Original/components/ssRewards/ssRewardsTable.tsx
> +    event: React.MouseEvent<HTMLButtonElement, MouseEvent> | null | unknown,
You mean VmPagination? Seems like we can just define it properly in prop types of VmPagination and then we dont need unknown.

2023-05-02 08:11 UTC, t0rbik commented
Could you merge prod into it?

2023-05-23 07:24 UTC, t0rbik commented
inaction. can be reopened.

2023-05-23 07:24 UTC, closed without merging