grouping nfts
Velocimeter/frontend pull request #81
Opened 2023-05-05 10:44 UTC by oxSaturn

Currently there's no way to tell right from the vote page which nfts have voted or reset:

<img width="607" alt="" src="https://user-images.githubusercontent.com/126733611/236435252-ffce3578-57aa-4cf0-93e4-47b49bc19bda.png">

You'll have to check the vest page first.

In this pr, we group nfts into two categories:

<img width="310" alt="" src="https://user-images.githubusercontent.com/126733611/236436064-7835800c-6348-4a5e-84a5-15c6b2b05d93.png">

And if you select those voted/reset nfts:

We'll show this warning:

<img width="671" alt="" src="https://user-images.githubusercontent.com/126733611/236436381-82923eee-a42a-46a2-a1bd-1b50e0346d4b.png">

Instead of an actionable button like below:

<img width="571" alt="" src="https://user-images.githubusercontent.com/126733611/236436451-30735da1-ce7e-4785-a74a-0c873688efa5.png">

And since users can tell right on the vote page the status of nfts, they're unlikely to do something described in https://github.com/Velocimeter/frontend/issues/75, hence we can hopefully avoid that issue.

2023-05-05 10:49 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVotes/ssVotes.tsx
> +                        <MenuItem
![](https://user-images.githubusercontent.com/126733611/236438673-e7e75bf5-2fdd-47f3-b9e5-5491f473d79d.png)

That's why I'm not introducing a customized component to avoid code duplication.

2023-05-05 10:49 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVotes/ssVotes.tsx
> +
See https://mui.com/material-ui/react-select/#grouping

2023-05-05 10:50 UTC, oxSaturn commented on Frontend-v1-Original/components/ssVotes/ssVotes.tsx
> +      }
Select votable NFTs first when possible.

2023-05-05 14:44 UTC, t0rbik approved these changes
looks very good

2023-05-07 04:58 UTC, t0rbik commented
When i first open vote page with 1 nft voted and 1 nft hasnt voted. it auto selects nft not voted in nft selector. But the ui shows votes for nft voted. because it has lower id so it comes first in array I guess and in prod it would select first my voted nft.

2023-05-07 04:59 UTC, t0rbik requested changes
When i first open vote page with 1 nft voted and 1 nft hasnt voted. it auto selects nft not voted in nft selector. But the ui shows votes for nft voted. because it has lower id so it comes first in array I guess and in prod it would select first my voted nft.

2023-05-08 10:48 UTC, t0rbik approved these changes
Awesome. Do you reckon we can delete expand more icon because it's not expandable?

2023-05-08 11:13 UTC, oxSaturn commented
> Awesome. Do you reckon we can delete expand more icon because it's not expandable?

The reason I added the expand more icon was to distinguish the heading since the default style sucks. But yeah, it would introduce ambiguity here.

2023-05-08 11:29 UTC, merged